### ISSUE TITLE
Alt bij img zetten

### ISSUE THREAD

**Issue by Pink-Mallow** [Ronabundy1/the-startup-responsive-interactieve-website#2]
Vergeet geen alt="'" in te voegen bij je img tag. Dit is goed voor screen readers. 

https://github.com/Ronabundy1/the-startup-responsive-interactieve-website/blob/e3e5a88dab2999d5cc2df2361a04a16db35bff9e/index.html#L72

Pak het zo aan als voorbeeld:
```html
<img src="icon" alt="een search icoon">
```

Hierbij een link voor meer uitleg:
[Alt attribute uitgelegd](https://www.freecodecamp.org/news/what-is-alt-text-image-alt-text-html-example/)

**Comment by Ronabundy1** [comment]
Ty
