### ISSUE TITLE
div tag open?

### ISSUE THREAD

**Issue by Pink-Mallow** [Ronabundy1/the-startup-responsive-interactieve-website#3]
Ik zie een div binnen een div (zoals je hieronder ziet) die open staat. 
https://github.com/Ronabundy1/the-startup-responsive-interactieve-website/blob/e3e5a88dab2999d5cc2df2361a04a16db35bff9e/index.html#L70-L75

Soms hoef je een tag niet te sluiten, maaarrr een advies:
Het beste is om het te sluiten erachter. Je moet wel voorzichtig zijn want een tag niet goed afsluiten kan soms ervoor zorgen dat de tags niet gelezen worden of de browser kan het niet verwerken.

**Comment by Ronabundy1** [comment]
ty
