### ISSUE TITLE
Fouten in <img> 

### ISSUE THREAD

**Issue by Vikkeyeftimov** [Ronabundy1/the-startup-responsive-interactieve-website#8]
Je hebt bij elke van je  <img> code een space tussen gedaan wat niet hoort'
![image](https://github.com/Ronabundy1/the-startup-responsive-interactieve-website/assets/144008940/cf5af512-d5db-44b3-b0c5-1ed03a1e03c4)
![image](https://github.com/Ronabundy1/the-startup-responsive-interactieve-website/assets/144008940/66e06a86-92bc-4adb-a8e9-91447df66365)

**Comment by Ronabundy1** [comment]
bedankt, space heb ik weggehaald voor mee overzicht
