### ISSUE TITLE
geen footer opener 

### ISSUE THREAD

**Issue by Vikkeyeftimov** [Ronabundy1/the-startup-responsive-interactieve-website#9]
je footer heeft geen openening 
![image](https://github.com/Ronabundy1/the-startup-responsive-interactieve-website/assets/144008940/b2c4ff2c-e33d-41f5-ada1-322ec26029bf)

**Comment by Ronabundy1** [comment]
bedankt, ik heb een footer opening toegevoegd aan mijn html
